# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-01 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.NullBooleanField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='', verbose_name='Data set')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-date'],
                'verbose_name': 'Query',
            },
        ),
        migrations.CreateModel(
            name='QueryException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traceback', models.TextField(default='')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checker.Query', verbose_name='Query set')),
            ],
            options={
                'verbose_name_plural': 'Query Exceptions',
                'ordering': ['-date'],
                'verbose_name': 'Query Exception',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default='', verbose_name='Data set')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checker.Query', verbose_name='Query set')),
            ],
            options={
                'verbose_name_plural': 'Results',
                'ordering': ['-id'],
                'verbose_name': 'Result',
            },
        ),
    ]
